CREATE TABLE IF NOT EXISTS nutrition_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    meal_type VARCHAR(50) NOT NULL DEFAULT 'snack',
    food_name VARCHAR(255) NOT NULL,
    quantity DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    unit VARCHAR(20) NOT NULL DEFAULT 'порц',
    calories INTEGER NOT NULL DEFAULT 0,
    protein DOUBLE PRECISION NOT NULL DEFAULT 0,
    fat DOUBLE PRECISION NOT NULL DEFAULT 0,
    carbs DOUBLE PRECISION NOT NULL DEFAULT 0,
    logged_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_nutrition_logs_user_date ON nutrition_logs(user_id, date);

CREATE TABLE IF NOT EXISTS user_nutrition_goals (
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    calorie_target INTEGER NOT NULL DEFAULT 2000,
    protein_target DOUBLE PRECISION NOT NULL DEFAULT 100,
    fat_target DOUBLE PRECISION NOT NULL DEFAULT 70,
    carbs_target DOUBLE PRECISION NOT NULL DEFAULT 250,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
