// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_fridge.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addFridgeMember = `-- name: AddFridgeMember :one
INSERT INTO fridge_members (fridge_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (fridge_id, user_id) DO UPDATE SET role = EXCLUDED.role
RETURNING fridge_id, user_id, role, joined_at
`

type AddFridgeMemberParams struct {
	FridgeID uuid.UUID
	UserID   uuid.UUID
	Role     string
}

func (q *Queries) AddFridgeMember(ctx context.Context, arg AddFridgeMemberParams) (FridgeMember, error) {
	row := q.db.QueryRow(ctx, addFridgeMember, arg.FridgeID, arg.UserID, arg.Role)
	var i FridgeMember
	err := row.Scan(
		&i.FridgeID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const createFridge = `-- name: CreateFridge :one
INSERT INTO fridges (name, owner_id)
VALUES ($1, $2)
RETURNING id, name, owner_id, created_at, updated_at
`

type CreateFridgeParams struct {
	Name    string
	OwnerID uuid.UUID
}

func (q *Queries) CreateFridge(ctx context.Context, arg CreateFridgeParams) (Fridge, error) {
	row := q.db.QueryRow(ctx, createFridge, arg.Name, arg.OwnerID)
	var i Fridge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, revoked_at, created_at
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, password_hash)
VALUES ($1, $2, $3)
RETURNING id, email, name, password_hash, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	Name         string
	PasswordHash string
}

type CreateUserRow struct {
	ID           uuid.UUID
	Email        string
	Name         string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Name, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFridge = `-- name: DeleteFridge :exec
DELETE FROM fridges
WHERE id = $1
`

func (q *Queries) DeleteFridge(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFridge, id)
	return err
}

const getFridgeByID = `-- name: GetFridgeByID :one
SELECT id, name, owner_id, created_at, updated_at
FROM fridges
WHERE id = $1
`

func (q *Queries) GetFridgeByID(ctx context.Context, id uuid.UUID) (Fridge, error) {
	row := q.db.QueryRow(ctx, getFridgeByID, id)
	var i Fridge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFridgeMember = `-- name: GetFridgeMember :one
SELECT fridge_id, user_id, role, joined_at
FROM fridge_members
WHERE fridge_id = $1 AND user_id = $2
`

type GetFridgeMemberParams struct {
	FridgeID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) GetFridgeMember(ctx context.Context, arg GetFridgeMemberParams) (FridgeMember, error) {
	row := q.db.QueryRow(ctx, getFridgeMember, arg.FridgeID, arg.UserID)
	var i FridgeMember
	err := row.Scan(
		&i.FridgeID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getFridgeMembers = `-- name: GetFridgeMembers :many
SELECT u.id, u.name, u.email, fm.role, fm.joined_at
FROM fridge_members fm
JOIN users u ON fm.user_id = u.id
WHERE fm.fridge_id = $1
ORDER BY fm.joined_at ASC
`

type GetFridgeMembersRow struct {
	ID       uuid.UUID
	Name     string
	Email    string
	Role     string
	JoinedAt time.Time
}

func (q *Queries) GetFridgeMembers(ctx context.Context, fridgeID uuid.UUID) ([]GetFridgeMembersRow, error) {
	rows, err := q.db.Query(ctx, getFridgeMembers, fridgeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFridgeMembersRow
	for rows.Next() {
		var i GetFridgeMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFridgesByUserID = `-- name: GetFridgesByUserID :many
SELECT f.id, f.name, f.owner_id, f.created_at, f.updated_at, fm.role
FROM fridges f
JOIN fridge_members fm ON f.id = fm.fridge_id
WHERE fm.user_id = $1
ORDER BY f.created_at ASC
`

type GetFridgesByUserIDRow struct {
	ID        uuid.UUID
	Name      string
	OwnerID   uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Role      string
}

func (q *Queries) GetFridgesByUserID(ctx context.Context, userID uuid.UUID) ([]GetFridgesByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getFridgesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFridgesByUserIDRow
	for rows.Next() {
		var i GetFridgesByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, created_at, updated_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           uuid.UUID
	Email        string
	Name         string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID        uuid.UUID
	Email     string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserFullByID = `-- name: GetUserFullByID :one
SELECT id, email, name, dietary_preferences, cuisine_preference, preferred_language, preferred_model, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserFullByIDRow struct {
	ID                 uuid.UUID
	Email              string
	Name               string
	DietaryPreferences string
	CuisinePreference  string
	PreferredLanguage  string
	PreferredModel     string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

func (q *Queries) GetUserFullByID(ctx context.Context, id uuid.UUID) (GetUserFullByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserFullByID, id)
	var i GetUserFullByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.DietaryPreferences,
		&i.CuisinePreference,
		&i.PreferredLanguage,
		&i.PreferredModel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPasswordByID = `-- name: GetUserPasswordByID :one
SELECT id, password_hash
FROM users
WHERE id = $1
`

type GetUserPasswordByIDRow struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) GetUserPasswordByID(ctx context.Context, id uuid.UUID) (GetUserPasswordByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserPasswordByID, id)
	var i GetUserPasswordByIDRow
	err := row.Scan(&i.ID, &i.PasswordHash)
	return i, err
}

const getValidRefreshTokenByHash = `-- name: GetValidRefreshTokenByHash :one
SELECT id, user_id, token_hash, expires_at, revoked_at, created_at
FROM refresh_tokens
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > NOW()
`

func (q *Queries) GetValidRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getValidRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const removeFridgeMember = `-- name: RemoveFridgeMember :exec
DELETE FROM fridge_members
WHERE fridge_id = $1 AND user_id = $2
`

type RemoveFridgeMemberParams struct {
	FridgeID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) RemoveFridgeMember(ctx context.Context, arg RemoveFridgeMemberParams) error {
	_, err := q.db.Exec(ctx, removeFridgeMember, arg.FridgeID, arg.UserID)
	return err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE token_hash = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET 
    name = $2,
    dietary_preferences = $3,
    cuisine_preference = $4,
    preferred_language = $5,
    preferred_model = $6,
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, name, dietary_preferences, cuisine_preference, preferred_language, preferred_model, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID                 uuid.UUID
	Name               string
	DietaryPreferences string
	CuisinePreference  string
	PreferredLanguage  string
	PreferredModel     string
}

type UpdateUserProfileRow struct {
	ID                 uuid.UUID
	Email              string
	Name               string
	DietaryPreferences string
	CuisinePreference  string
	PreferredLanguage  string
	PreferredModel     string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.Name,
		arg.DietaryPreferences,
		arg.CuisinePreference,
		arg.PreferredLanguage,
		arg.PreferredModel,
	)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.DietaryPreferences,
		&i.CuisinePreference,
		&i.PreferredLanguage,
		&i.PreferredModel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
