// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chef_chat.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const clearChefMessages = `-- name: ClearChefMessages :exec
DELETE FROM chef_messages
WHERE fridge_id = $1
`

func (q *Queries) ClearChefMessages(ctx context.Context, fridgeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearChefMessages, fridgeID)
	return err
}

const createChefMessage = `-- name: CreateChefMessage :one
INSERT INTO chef_messages (
    fridge_id, user_id, role, content, recipe_data, shopping_suggestions
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, fridge_id, user_id, role, content, recipe_data, shopping_suggestions, created_at
`

type CreateChefMessageParams struct {
	FridgeID            uuid.UUID
	UserID              uuid.UUID
	Role                string
	Content             string
	RecipeData          []byte
	ShoppingSuggestions []byte
}

func (q *Queries) CreateChefMessage(ctx context.Context, arg CreateChefMessageParams) (ChefMessage, error) {
	row := q.db.QueryRow(ctx, createChefMessage,
		arg.FridgeID,
		arg.UserID,
		arg.Role,
		arg.Content,
		arg.RecipeData,
		arg.ShoppingSuggestions,
	)
	var i ChefMessage
	err := row.Scan(
		&i.ID,
		&i.FridgeID,
		&i.UserID,
		&i.Role,
		&i.Content,
		&i.RecipeData,
		&i.ShoppingSuggestions,
		&i.CreatedAt,
	)
	return i, err
}

const listChefMessages = `-- name: ListChefMessages :many
SELECT id, fridge_id, user_id, role, content, recipe_data, shopping_suggestions, created_at
FROM chef_messages
WHERE fridge_id = $1
ORDER BY created_at ASC
LIMIT $2
`

type ListChefMessagesParams struct {
	FridgeID uuid.UUID
	Limit    int32
}

func (q *Queries) ListChefMessages(ctx context.Context, arg ListChefMessagesParams) ([]ChefMessage, error) {
	rows, err := q.db.Query(ctx, listChefMessages, arg.FridgeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChefMessage
	for rows.Next() {
		var i ChefMessage
		if err := rows.Scan(
			&i.ID,
			&i.FridgeID,
			&i.UserID,
			&i.Role,
			&i.Content,
			&i.RecipeData,
			&i.ShoppingSuggestions,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
