// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ChefMessage struct {
	ID                  uuid.UUID
	FridgeID            uuid.UUID
	UserID              uuid.UUID
	Role                string
	Content             string
	RecipeData          []byte
	ShoppingSuggestions []byte
	CreatedAt           time.Time
}

type Fridge struct {
	ID        uuid.UUID
	Name      string
	OwnerID   uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type FridgeMember struct {
	FridgeID uuid.UUID
	UserID   uuid.UUID
	Role     string
	JoinedAt time.Time
}

type MealPlan struct {
	ID          uuid.UUID
	FridgeID    uuid.UUID
	UserID      uuid.UUID
	Date        pgtype.Date
	MealType    string
	RecipeTitle string
	RecipeID    pgtype.UUID
	Calories    int32
	Protein     float64
	Fat         float64
	Carbs       float64
	IsCompleted bool
	Notes       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type NutritionLog struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	Date     pgtype.Date
	MealType string
	FoodName string
	Quantity float64
	Unit     string
	Calories int32
	Protein  float64
	Fat      float64
	Carbs    float64
	LoggedAt time.Time
}

type PendingRegistration struct {
	ID               uuid.UUID
	Email            string
	Name             string
	PasswordHash     string
	VerificationCode string
	ExpiresAt        time.Time
	CreatedAt        time.Time
}

type Product struct {
	ID         uuid.UUID
	FridgeID   uuid.UUID
	Name       string
	Category   string
	Quantity   float64
	Unit       string
	ExpiryDate pgtype.Date
	Calories   int32
	Protein    float64
	Fat        float64
	Carbs      float64
	Notes      string
	CreatedBy  uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	RevokedAt pgtype.Timestamptz
	CreatedAt time.Time
}

type SavedRecipe struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	FridgeID     pgtype.UUID
	Title        string
	Description  string
	Ingredients  []byte
	Steps        []byte
	Calories     int32
	Protein      float64
	Fat          float64
	Carbs        float64
	PrepTimeMins int32
	CookTimeMins int32
	Servings     int32
	CreatedAt    time.Time
}

type ShoppingItem struct {
	ID        uuid.UUID
	FridgeID  uuid.UUID
	Name      string
	Category  string
	Quantity  float64
	Unit      string
	IsBought  bool
	CreatedBy uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID                 uuid.UUID
	Email              string
	Name               string
	PasswordHash       string
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DietaryPreferences string
	CuisinePreference  string
	PreferredLanguage  string
	PreferredModel     string
}

type UserNutritionGoal struct {
	UserID        uuid.UUID
	CalorieTarget int32
	ProteinTarget float64
	FatTarget     float64
	CarbsTarget   float64
	UpdatedAt     time.Time
}
