// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nutrition.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNutritionLog = `-- name: CreateNutritionLog :one
INSERT INTO nutrition_logs (
    user_id, date, meal_type, food_name, quantity, unit, calories, protein, fat, carbs
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, user_id, date, meal_type, food_name, quantity, unit, calories, protein, fat, carbs, logged_at
`

type CreateNutritionLogParams struct {
	UserID   uuid.UUID
	Date     pgtype.Date
	MealType string
	FoodName string
	Quantity float64
	Unit     string
	Calories int32
	Protein  float64
	Fat      float64
	Carbs    float64
}

func (q *Queries) CreateNutritionLog(ctx context.Context, arg CreateNutritionLogParams) (NutritionLog, error) {
	row := q.db.QueryRow(ctx, createNutritionLog,
		arg.UserID,
		arg.Date,
		arg.MealType,
		arg.FoodName,
		arg.Quantity,
		arg.Unit,
		arg.Calories,
		arg.Protein,
		arg.Fat,
		arg.Carbs,
	)
	var i NutritionLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.MealType,
		&i.FoodName,
		&i.Quantity,
		&i.Unit,
		&i.Calories,
		&i.Protein,
		&i.Fat,
		&i.Carbs,
		&i.LoggedAt,
	)
	return i, err
}

const deleteNutritionLog = `-- name: DeleteNutritionLog :exec
DELETE FROM nutrition_logs
WHERE id = $1 AND user_id = $2
`

type DeleteNutritionLogParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteNutritionLog(ctx context.Context, arg DeleteNutritionLogParams) error {
	_, err := q.db.Exec(ctx, deleteNutritionLog, arg.ID, arg.UserID)
	return err
}

const getNutritionGoals = `-- name: GetNutritionGoals :one
SELECT user_id, calorie_target, protein_target, fat_target, carbs_target, updated_at FROM user_nutrition_goals
WHERE user_id = $1
`

func (q *Queries) GetNutritionGoals(ctx context.Context, userID uuid.UUID) (UserNutritionGoal, error) {
	row := q.db.QueryRow(ctx, getNutritionGoals, userID)
	var i UserNutritionGoal
	err := row.Scan(
		&i.UserID,
		&i.CalorieTarget,
		&i.ProteinTarget,
		&i.FatTarget,
		&i.CarbsTarget,
		&i.UpdatedAt,
	)
	return i, err
}

const listNutritionLogsByDate = `-- name: ListNutritionLogsByDate :many
SELECT id, user_id, date, meal_type, food_name, quantity, unit, calories, protein, fat, carbs, logged_at FROM nutrition_logs
WHERE user_id = $1 AND date = $2
ORDER BY logged_at ASC
`

type ListNutritionLogsByDateParams struct {
	UserID uuid.UUID
	Date   pgtype.Date
}

func (q *Queries) ListNutritionLogsByDate(ctx context.Context, arg ListNutritionLogsByDateParams) ([]NutritionLog, error) {
	rows, err := q.db.Query(ctx, listNutritionLogsByDate, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NutritionLog
	for rows.Next() {
		var i NutritionLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.MealType,
			&i.FoodName,
			&i.Quantity,
			&i.Unit,
			&i.Calories,
			&i.Protein,
			&i.Fat,
			&i.Carbs,
			&i.LoggedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNutritionGoals = `-- name: UpsertNutritionGoals :one
INSERT INTO user_nutrition_goals (user_id, calorie_target, protein_target, fat_target, carbs_target, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (user_id) DO UPDATE
SET calorie_target = EXCLUDED.calorie_target,
    protein_target = EXCLUDED.protein_target,
    fat_target = EXCLUDED.fat_target,
    carbs_target = EXCLUDED.carbs_target,
    updated_at = NOW()
RETURNING user_id, calorie_target, protein_target, fat_target, carbs_target, updated_at
`

type UpsertNutritionGoalsParams struct {
	UserID        uuid.UUID
	CalorieTarget int32
	ProteinTarget float64
	FatTarget     float64
	CarbsTarget   float64
}

func (q *Queries) UpsertNutritionGoals(ctx context.Context, arg UpsertNutritionGoalsParams) (UserNutritionGoal, error) {
	row := q.db.QueryRow(ctx, upsertNutritionGoals,
		arg.UserID,
		arg.CalorieTarget,
		arg.ProteinTarget,
		arg.FatTarget,
		arg.CarbsTarget,
	)
	var i UserNutritionGoal
	err := row.Scan(
		&i.UserID,
		&i.CalorieTarget,
		&i.ProteinTarget,
		&i.FatTarget,
		&i.CarbsTarget,
		&i.UpdatedAt,
	)
	return i, err
}
