// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: planner.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearMealPlansByDateRange = `-- name: ClearMealPlansByDateRange :exec
DELETE FROM meal_plans
WHERE fridge_id = $1 AND date >= $2 AND date <= $3
`

type ClearMealPlansByDateRangeParams struct {
	FridgeID uuid.UUID
	Date     pgtype.Date
	Date_2   pgtype.Date
}

func (q *Queries) ClearMealPlansByDateRange(ctx context.Context, arg ClearMealPlansByDateRangeParams) error {
	_, err := q.db.Exec(ctx, clearMealPlansByDateRange, arg.FridgeID, arg.Date, arg.Date_2)
	return err
}

const countMealPlansByFridgeAndDate = `-- name: CountMealPlansByFridgeAndDate :one
SELECT COUNT(*)
FROM meal_plans
WHERE fridge_id = $1 AND date = $2
`

type CountMealPlansByFridgeAndDateParams struct {
	FridgeID uuid.UUID
	Date     pgtype.Date
}

func (q *Queries) CountMealPlansByFridgeAndDate(ctx context.Context, arg CountMealPlansByFridgeAndDateParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMealPlansByFridgeAndDate, arg.FridgeID, arg.Date)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMealPlan = `-- name: CreateMealPlan :one
INSERT INTO meal_plans (
    fridge_id, user_id, date, meal_type, recipe_title, recipe_id, calories, protein, fat, carbs, notes, recipe_data
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, fridge_id, user_id, date, meal_type, recipe_title, recipe_id, calories, protein, fat, carbs, is_completed, notes, recipe_data, created_at, updated_at
`

type CreateMealPlanParams struct {
	FridgeID    uuid.UUID
	UserID      uuid.UUID
	Date        pgtype.Date
	MealType    string
	RecipeTitle string
	RecipeID    pgtype.UUID
	Calories    int32
	Protein     float64
	Fat         float64
	Carbs       float64
	Notes       string
	RecipeData  []byte
}

type CreateMealPlanRow struct {
	ID          uuid.UUID
	FridgeID    uuid.UUID
	UserID      uuid.UUID
	Date        pgtype.Date
	MealType    string
	RecipeTitle string
	RecipeID    pgtype.UUID
	Calories    int32
	Protein     float64
	Fat         float64
	Carbs       float64
	IsCompleted bool
	Notes       string
	RecipeData  []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateMealPlan(ctx context.Context, arg CreateMealPlanParams) (CreateMealPlanRow, error) {
	row := q.db.QueryRow(ctx, createMealPlan,
		arg.FridgeID,
		arg.UserID,
		arg.Date,
		arg.MealType,
		arg.RecipeTitle,
		arg.RecipeID,
		arg.Calories,
		arg.Protein,
		arg.Fat,
		arg.Carbs,
		arg.Notes,
		arg.RecipeData,
	)
	var i CreateMealPlanRow
	err := row.Scan(
		&i.ID,
		&i.FridgeID,
		&i.UserID,
		&i.Date,
		&i.MealType,
		&i.RecipeTitle,
		&i.RecipeID,
		&i.Calories,
		&i.Protein,
		&i.Fat,
		&i.Carbs,
		&i.IsCompleted,
		&i.Notes,
		&i.RecipeData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMealPlan = `-- name: DeleteMealPlan :exec
DELETE FROM meal_plans
WHERE id = $1 AND fridge_id = $2
`

type DeleteMealPlanParams struct {
	ID       uuid.UUID
	FridgeID uuid.UUID
}

func (q *Queries) DeleteMealPlan(ctx context.Context, arg DeleteMealPlanParams) error {
	_, err := q.db.Exec(ctx, deleteMealPlan, arg.ID, arg.FridgeID)
	return err
}

const deleteMealPlanByFridgeDateAndType = `-- name: DeleteMealPlanByFridgeDateAndType :exec
DELETE FROM meal_plans
WHERE fridge_id = $1 AND date = $2 AND meal_type = $3
`

type DeleteMealPlanByFridgeDateAndTypeParams struct {
	FridgeID uuid.UUID
	Date     pgtype.Date
	MealType string
}

func (q *Queries) DeleteMealPlanByFridgeDateAndType(ctx context.Context, arg DeleteMealPlanByFridgeDateAndTypeParams) error {
	_, err := q.db.Exec(ctx, deleteMealPlanByFridgeDateAndType, arg.FridgeID, arg.Date, arg.MealType)
	return err
}

const getMealPlanByID = `-- name: GetMealPlanByID :one
SELECT id, fridge_id, user_id, date, meal_type, recipe_title, recipe_id, calories, protein, fat, carbs, is_completed, notes, recipe_data, created_at, updated_at
FROM meal_plans
WHERE id = $1 AND fridge_id = $2
`

type GetMealPlanByIDParams struct {
	ID       uuid.UUID
	FridgeID uuid.UUID
}

type GetMealPlanByIDRow struct {
	ID          uuid.UUID
	FridgeID    uuid.UUID
	UserID      uuid.UUID
	Date        pgtype.Date
	MealType    string
	RecipeTitle string
	RecipeID    pgtype.UUID
	Calories    int32
	Protein     float64
	Fat         float64
	Carbs       float64
	IsCompleted bool
	Notes       string
	RecipeData  []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetMealPlanByID(ctx context.Context, arg GetMealPlanByIDParams) (GetMealPlanByIDRow, error) {
	row := q.db.QueryRow(ctx, getMealPlanByID, arg.ID, arg.FridgeID)
	var i GetMealPlanByIDRow
	err := row.Scan(
		&i.ID,
		&i.FridgeID,
		&i.UserID,
		&i.Date,
		&i.MealType,
		&i.RecipeTitle,
		&i.RecipeID,
		&i.Calories,
		&i.Protein,
		&i.Fat,
		&i.Carbs,
		&i.IsCompleted,
		&i.Notes,
		&i.RecipeData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMealPlansByFridgeAndDate = `-- name: ListMealPlansByFridgeAndDate :many
SELECT id, fridge_id, user_id, date, meal_type, recipe_title, recipe_id, calories, protein, fat, carbs, is_completed, notes, recipe_data, created_at, updated_at
FROM meal_plans
WHERE fridge_id = $1 AND date = $2
ORDER BY 
    CASE meal_type 
        WHEN 'breakfast' THEN 1 
        WHEN 'lunch' THEN 2 
        WHEN 'dinner' THEN 3 
        ELSE 4 
    END
`

type ListMealPlansByFridgeAndDateParams struct {
	FridgeID uuid.UUID
	Date     pgtype.Date
}

type ListMealPlansByFridgeAndDateRow struct {
	ID          uuid.UUID
	FridgeID    uuid.UUID
	UserID      uuid.UUID
	Date        pgtype.Date
	MealType    string
	RecipeTitle string
	RecipeID    pgtype.UUID
	Calories    int32
	Protein     float64
	Fat         float64
	Carbs       float64
	IsCompleted bool
	Notes       string
	RecipeData  []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) ListMealPlansByFridgeAndDate(ctx context.Context, arg ListMealPlansByFridgeAndDateParams) ([]ListMealPlansByFridgeAndDateRow, error) {
	rows, err := q.db.Query(ctx, listMealPlansByFridgeAndDate, arg.FridgeID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMealPlansByFridgeAndDateRow
	for rows.Next() {
		var i ListMealPlansByFridgeAndDateRow
		if err := rows.Scan(
			&i.ID,
			&i.FridgeID,
			&i.UserID,
			&i.Date,
			&i.MealType,
			&i.RecipeTitle,
			&i.RecipeID,
			&i.Calories,
			&i.Protein,
			&i.Fat,
			&i.Carbs,
			&i.IsCompleted,
			&i.Notes,
			&i.RecipeData,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealPlansByFridgeAndDateRange = `-- name: ListMealPlansByFridgeAndDateRange :many
SELECT id, fridge_id, user_id, date, meal_type, recipe_title, recipe_id, calories, protein, fat, carbs, is_completed, notes, recipe_data, created_at, updated_at
FROM meal_plans
WHERE fridge_id = $1 AND date >= $2 AND date <= $3
ORDER BY date ASC, 
    CASE meal_type 
        WHEN 'breakfast' THEN 1 
        WHEN 'lunch' THEN 2 
        WHEN 'dinner' THEN 3 
        ELSE 4 
    END
`

type ListMealPlansByFridgeAndDateRangeParams struct {
	FridgeID uuid.UUID
	Date     pgtype.Date
	Date_2   pgtype.Date
}

type ListMealPlansByFridgeAndDateRangeRow struct {
	ID          uuid.UUID
	FridgeID    uuid.UUID
	UserID      uuid.UUID
	Date        pgtype.Date
	MealType    string
	RecipeTitle string
	RecipeID    pgtype.UUID
	Calories    int32
	Protein     float64
	Fat         float64
	Carbs       float64
	IsCompleted bool
	Notes       string
	RecipeData  []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) ListMealPlansByFridgeAndDateRange(ctx context.Context, arg ListMealPlansByFridgeAndDateRangeParams) ([]ListMealPlansByFridgeAndDateRangeRow, error) {
	rows, err := q.db.Query(ctx, listMealPlansByFridgeAndDateRange, arg.FridgeID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMealPlansByFridgeAndDateRangeRow
	for rows.Next() {
		var i ListMealPlansByFridgeAndDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.FridgeID,
			&i.UserID,
			&i.Date,
			&i.MealType,
			&i.RecipeTitle,
			&i.RecipeID,
			&i.Calories,
			&i.Protein,
			&i.Fat,
			&i.Carbs,
			&i.IsCompleted,
			&i.Notes,
			&i.RecipeData,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleMealPlanCompleted = `-- name: ToggleMealPlanCompleted :one
UPDATE meal_plans
SET is_completed = $3, updated_at = NOW()
WHERE id = $1 AND fridge_id = $2
RETURNING id, fridge_id, user_id, date, meal_type, recipe_title, recipe_id, calories, protein, fat, carbs, is_completed, notes, recipe_data, created_at, updated_at
`

type ToggleMealPlanCompletedParams struct {
	ID          uuid.UUID
	FridgeID    uuid.UUID
	IsCompleted bool
}

type ToggleMealPlanCompletedRow struct {
	ID          uuid.UUID
	FridgeID    uuid.UUID
	UserID      uuid.UUID
	Date        pgtype.Date
	MealType    string
	RecipeTitle string
	RecipeID    pgtype.UUID
	Calories    int32
	Protein     float64
	Fat         float64
	Carbs       float64
	IsCompleted bool
	Notes       string
	RecipeData  []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) ToggleMealPlanCompleted(ctx context.Context, arg ToggleMealPlanCompletedParams) (ToggleMealPlanCompletedRow, error) {
	row := q.db.QueryRow(ctx, toggleMealPlanCompleted, arg.ID, arg.FridgeID, arg.IsCompleted)
	var i ToggleMealPlanCompletedRow
	err := row.Scan(
		&i.ID,
		&i.FridgeID,
		&i.UserID,
		&i.Date,
		&i.MealType,
		&i.RecipeTitle,
		&i.RecipeID,
		&i.Calories,
		&i.Protein,
		&i.Fat,
		&i.Carbs,
		&i.IsCompleted,
		&i.Notes,
		&i.RecipeData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMealPlan = `-- name: UpdateMealPlan :one
UPDATE meal_plans
SET 
    date = $3,
    meal_type = $4,
    recipe_title = $5,
    recipe_id = $6,
    calories = $7,
    protein = $8,
    fat = $9,
    carbs = $10,
    notes = $11,
    recipe_data = $12,
    updated_at = NOW()
WHERE id = $1 AND fridge_id = $2
RETURNING id, fridge_id, user_id, date, meal_type, recipe_title, recipe_id, calories, protein, fat, carbs, is_completed, notes, recipe_data, created_at, updated_at
`

type UpdateMealPlanParams struct {
	ID          uuid.UUID
	FridgeID    uuid.UUID
	Date        pgtype.Date
	MealType    string
	RecipeTitle string
	RecipeID    pgtype.UUID
	Calories    int32
	Protein     float64
	Fat         float64
	Carbs       float64
	Notes       string
	RecipeData  []byte
}

type UpdateMealPlanRow struct {
	ID          uuid.UUID
	FridgeID    uuid.UUID
	UserID      uuid.UUID
	Date        pgtype.Date
	MealType    string
	RecipeTitle string
	RecipeID    pgtype.UUID
	Calories    int32
	Protein     float64
	Fat         float64
	Carbs       float64
	IsCompleted bool
	Notes       string
	RecipeData  []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) UpdateMealPlan(ctx context.Context, arg UpdateMealPlanParams) (UpdateMealPlanRow, error) {
	row := q.db.QueryRow(ctx, updateMealPlan,
		arg.ID,
		arg.FridgeID,
		arg.Date,
		arg.MealType,
		arg.RecipeTitle,
		arg.RecipeID,
		arg.Calories,
		arg.Protein,
		arg.Fat,
		arg.Carbs,
		arg.Notes,
		arg.RecipeData,
	)
	var i UpdateMealPlanRow
	err := row.Scan(
		&i.ID,
		&i.FridgeID,
		&i.UserID,
		&i.Date,
		&i.MealType,
		&i.RecipeTitle,
		&i.RecipeID,
		&i.Calories,
		&i.Protein,
		&i.Fat,
		&i.Carbs,
		&i.IsCompleted,
		&i.Notes,
		&i.RecipeData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
