// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: planner.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearMealPlansByDateRange = `-- name: ClearMealPlansByDateRange :exec
DELETE FROM meal_plans
WHERE fridge_id = $1 AND date >= $2 AND date <= $3
`

type ClearMealPlansByDateRangeParams struct {
	FridgeID uuid.UUID
	Date     pgtype.Date
	Date_2   pgtype.Date
}

func (q *Queries) ClearMealPlansByDateRange(ctx context.Context, arg ClearMealPlansByDateRangeParams) error {
	_, err := q.db.Exec(ctx, clearMealPlansByDateRange, arg.FridgeID, arg.Date, arg.Date_2)
	return err
}

const createMealPlan = `-- name: CreateMealPlan :one
INSERT INTO meal_plans (
    fridge_id, user_id, date, meal_type, recipe_title, recipe_id, calories, protein, fat, carbs, notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, fridge_id, user_id, date, meal_type, recipe_title, recipe_id, calories, protein, fat, carbs, is_completed, notes, created_at, updated_at
`

type CreateMealPlanParams struct {
	FridgeID    uuid.UUID
	UserID      uuid.UUID
	Date        pgtype.Date
	MealType    string
	RecipeTitle string
	RecipeID    pgtype.UUID
	Calories    int32
	Protein     float64
	Fat         float64
	Carbs       float64
	Notes       string
}

func (q *Queries) CreateMealPlan(ctx context.Context, arg CreateMealPlanParams) (MealPlan, error) {
	row := q.db.QueryRow(ctx, createMealPlan,
		arg.FridgeID,
		arg.UserID,
		arg.Date,
		arg.MealType,
		arg.RecipeTitle,
		arg.RecipeID,
		arg.Calories,
		arg.Protein,
		arg.Fat,
		arg.Carbs,
		arg.Notes,
	)
	var i MealPlan
	err := row.Scan(
		&i.ID,
		&i.FridgeID,
		&i.UserID,
		&i.Date,
		&i.MealType,
		&i.RecipeTitle,
		&i.RecipeID,
		&i.Calories,
		&i.Protein,
		&i.Fat,
		&i.Carbs,
		&i.IsCompleted,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMealPlan = `-- name: DeleteMealPlan :exec
DELETE FROM meal_plans
WHERE id = $1 AND fridge_id = $2
`

type DeleteMealPlanParams struct {
	ID       uuid.UUID
	FridgeID uuid.UUID
}

func (q *Queries) DeleteMealPlan(ctx context.Context, arg DeleteMealPlanParams) error {
	_, err := q.db.Exec(ctx, deleteMealPlan, arg.ID, arg.FridgeID)
	return err
}

const getMealPlanByID = `-- name: GetMealPlanByID :one
SELECT id, fridge_id, user_id, date, meal_type, recipe_title, recipe_id, calories, protein, fat, carbs, is_completed, notes, created_at, updated_at
FROM meal_plans
WHERE id = $1 AND fridge_id = $2
`

type GetMealPlanByIDParams struct {
	ID       uuid.UUID
	FridgeID uuid.UUID
}

func (q *Queries) GetMealPlanByID(ctx context.Context, arg GetMealPlanByIDParams) (MealPlan, error) {
	row := q.db.QueryRow(ctx, getMealPlanByID, arg.ID, arg.FridgeID)
	var i MealPlan
	err := row.Scan(
		&i.ID,
		&i.FridgeID,
		&i.UserID,
		&i.Date,
		&i.MealType,
		&i.RecipeTitle,
		&i.RecipeID,
		&i.Calories,
		&i.Protein,
		&i.Fat,
		&i.Carbs,
		&i.IsCompleted,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMealPlansByFridgeAndDateRange = `-- name: ListMealPlansByFridgeAndDateRange :many
SELECT id, fridge_id, user_id, date, meal_type, recipe_title, recipe_id, calories, protein, fat, carbs, is_completed, notes, created_at, updated_at
FROM meal_plans
WHERE fridge_id = $1 AND date >= $2 AND date <= $3
ORDER BY date ASC, 
    CASE meal_type 
        WHEN 'breakfast' THEN 1 
        WHEN 'lunch' THEN 2 
        WHEN 'dinner' THEN 3 
        ELSE 4 
    END
`

type ListMealPlansByFridgeAndDateRangeParams struct {
	FridgeID uuid.UUID
	Date     pgtype.Date
	Date_2   pgtype.Date
}

func (q *Queries) ListMealPlansByFridgeAndDateRange(ctx context.Context, arg ListMealPlansByFridgeAndDateRangeParams) ([]MealPlan, error) {
	rows, err := q.db.Query(ctx, listMealPlansByFridgeAndDateRange, arg.FridgeID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MealPlan
	for rows.Next() {
		var i MealPlan
		if err := rows.Scan(
			&i.ID,
			&i.FridgeID,
			&i.UserID,
			&i.Date,
			&i.MealType,
			&i.RecipeTitle,
			&i.RecipeID,
			&i.Calories,
			&i.Protein,
			&i.Fat,
			&i.Carbs,
			&i.IsCompleted,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleMealPlanCompleted = `-- name: ToggleMealPlanCompleted :one
UPDATE meal_plans
SET is_completed = $3, updated_at = NOW()
WHERE id = $1 AND fridge_id = $2
RETURNING id, fridge_id, user_id, date, meal_type, recipe_title, recipe_id, calories, protein, fat, carbs, is_completed, notes, created_at, updated_at
`

type ToggleMealPlanCompletedParams struct {
	ID          uuid.UUID
	FridgeID    uuid.UUID
	IsCompleted bool
}

func (q *Queries) ToggleMealPlanCompleted(ctx context.Context, arg ToggleMealPlanCompletedParams) (MealPlan, error) {
	row := q.db.QueryRow(ctx, toggleMealPlanCompleted, arg.ID, arg.FridgeID, arg.IsCompleted)
	var i MealPlan
	err := row.Scan(
		&i.ID,
		&i.FridgeID,
		&i.UserID,
		&i.Date,
		&i.MealType,
		&i.RecipeTitle,
		&i.RecipeID,
		&i.Calories,
		&i.Protein,
		&i.Fat,
		&i.Carbs,
		&i.IsCompleted,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMealPlan = `-- name: UpdateMealPlan :one
UPDATE meal_plans
SET 
    date = $3,
    meal_type = $4,
    recipe_title = $5,
    recipe_id = $6,
    calories = $7,
    protein = $8,
    fat = $9,
    carbs = $10,
    notes = $11,
    updated_at = NOW()
WHERE id = $1 AND fridge_id = $2
RETURNING id, fridge_id, user_id, date, meal_type, recipe_title, recipe_id, calories, protein, fat, carbs, is_completed, notes, created_at, updated_at
`

type UpdateMealPlanParams struct {
	ID          uuid.UUID
	FridgeID    uuid.UUID
	Date        pgtype.Date
	MealType    string
	RecipeTitle string
	RecipeID    pgtype.UUID
	Calories    int32
	Protein     float64
	Fat         float64
	Carbs       float64
	Notes       string
}

func (q *Queries) UpdateMealPlan(ctx context.Context, arg UpdateMealPlanParams) (MealPlan, error) {
	row := q.db.QueryRow(ctx, updateMealPlan,
		arg.ID,
		arg.FridgeID,
		arg.Date,
		arg.MealType,
		arg.RecipeTitle,
		arg.RecipeID,
		arg.Calories,
		arg.Protein,
		arg.Fat,
		arg.Carbs,
		arg.Notes,
	)
	var i MealPlan
	err := row.Scan(
		&i.ID,
		&i.FridgeID,
		&i.UserID,
		&i.Date,
		&i.MealType,
		&i.RecipeTitle,
		&i.RecipeID,
		&i.Calories,
		&i.Protein,
		&i.Fat,
		&i.Carbs,
		&i.IsCompleted,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
