// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    fridge_id, name, category, quantity, unit, expiry_date, calories, protein, fat, carbs, notes, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, fridge_id, name, category, quantity, unit, expiry_date, calories, protein, fat, carbs, notes, created_by, created_at, updated_at
`

type CreateProductParams struct {
	FridgeID   uuid.UUID
	Name       string
	Category   string
	Quantity   float64
	Unit       string
	ExpiryDate pgtype.Date
	Calories   int32
	Protein    float64
	Fat        float64
	Carbs      float64
	Notes      string
	CreatedBy  uuid.UUID
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.FridgeID,
		arg.Name,
		arg.Category,
		arg.Quantity,
		arg.Unit,
		arg.ExpiryDate,
		arg.Calories,
		arg.Protein,
		arg.Fat,
		arg.Carbs,
		arg.Notes,
		arg.CreatedBy,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.FridgeID,
		&i.Name,
		&i.Category,
		&i.Quantity,
		&i.Unit,
		&i.ExpiryDate,
		&i.Calories,
		&i.Protein,
		&i.Fat,
		&i.Carbs,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllProductsByFridge = `-- name: DeleteAllProductsByFridge :exec
DELETE FROM products
WHERE fridge_id = $1
`

func (q *Queries) DeleteAllProductsByFridge(ctx context.Context, fridgeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllProductsByFridge, fridgeID)
	return err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE id = $1 AND fridge_id = $2
`

type DeleteProductParams struct {
	ID       uuid.UUID
	FridgeID uuid.UUID
}

func (q *Queries) DeleteProduct(ctx context.Context, arg DeleteProductParams) error {
	_, err := q.db.Exec(ctx, deleteProduct, arg.ID, arg.FridgeID)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, fridge_id, name, category, quantity, unit, expiry_date, calories, protein, fat, carbs, notes, created_by, created_at, updated_at FROM products
WHERE id = $1 AND fridge_id = $2
`

type GetProductByIDParams struct {
	ID       uuid.UUID
	FridgeID uuid.UUID
}

func (q *Queries) GetProductByID(ctx context.Context, arg GetProductByIDParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, arg.ID, arg.FridgeID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.FridgeID,
		&i.Name,
		&i.Category,
		&i.Quantity,
		&i.Unit,
		&i.ExpiryDate,
		&i.Calories,
		&i.Protein,
		&i.Fat,
		&i.Carbs,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProductsByFridge = `-- name: ListProductsByFridge :many
SELECT id, fridge_id, name, category, quantity, unit, expiry_date, calories, protein, fat, carbs, notes, created_by, created_at, updated_at FROM products
WHERE fridge_id = $1
ORDER BY expiry_date ASC NULLS LAST, created_at DESC
`

func (q *Queries) ListProductsByFridge(ctx context.Context, fridgeID uuid.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByFridge, fridgeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.FridgeID,
			&i.Name,
			&i.Category,
			&i.Quantity,
			&i.Unit,
			&i.ExpiryDate,
			&i.Calories,
			&i.Protein,
			&i.Fat,
			&i.Carbs,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $3,
    category = $4,
    quantity = $5,
    unit = $6,
    expiry_date = $7,
    calories = $8,
    protein = $9,
    fat = $10,
    carbs = $11,
    notes = $12,
    updated_at = NOW()
WHERE id = $1 AND fridge_id = $2
RETURNING id, fridge_id, name, category, quantity, unit, expiry_date, calories, protein, fat, carbs, notes, created_by, created_at, updated_at
`

type UpdateProductParams struct {
	ID         uuid.UUID
	FridgeID   uuid.UUID
	Name       string
	Category   string
	Quantity   float64
	Unit       string
	ExpiryDate pgtype.Date
	Calories   int32
	Protein    float64
	Fat        float64
	Carbs      float64
	Notes      string
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.FridgeID,
		arg.Name,
		arg.Category,
		arg.Quantity,
		arg.Unit,
		arg.ExpiryDate,
		arg.Calories,
		arg.Protein,
		arg.Fat,
		arg.Carbs,
		arg.Notes,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.FridgeID,
		&i.Name,
		&i.Category,
		&i.Quantity,
		&i.Unit,
		&i.ExpiryDate,
		&i.Calories,
		&i.Protein,
		&i.Fat,
		&i.Carbs,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProductQuantity = `-- name: UpdateProductQuantity :one
UPDATE products
SET quantity = $3,
    updated_at = NOW()
WHERE id = $1 AND fridge_id = $2
RETURNING id, fridge_id, name, category, quantity, unit, expiry_date, calories, protein, fat, carbs, notes, created_by, created_at, updated_at
`

type UpdateProductQuantityParams struct {
	ID       uuid.UUID
	FridgeID uuid.UUID
	Quantity float64
}

func (q *Queries) UpdateProductQuantity(ctx context.Context, arg UpdateProductQuantityParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductQuantity, arg.ID, arg.FridgeID, arg.Quantity)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.FridgeID,
		&i.Name,
		&i.Category,
		&i.Quantity,
		&i.Unit,
		&i.ExpiryDate,
		&i.Calories,
		&i.Protein,
		&i.Fat,
		&i.Carbs,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProductQuantityAndUnit = `-- name: UpdateProductQuantityAndUnit :one
UPDATE products
SET quantity = $3,
    unit = $4,
    updated_at = NOW()
WHERE id = $1 AND fridge_id = $2
RETURNING id, fridge_id, name, category, quantity, unit, expiry_date, calories, protein, fat, carbs, notes, created_by, created_at, updated_at
`

type UpdateProductQuantityAndUnitParams struct {
	ID       uuid.UUID
	FridgeID uuid.UUID
	Quantity float64
	Unit     string
}

func (q *Queries) UpdateProductQuantityAndUnit(ctx context.Context, arg UpdateProductQuantityAndUnitParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductQuantityAndUnit, arg.ID, arg.FridgeID, arg.Quantity, arg.Unit)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.FridgeID,
		&i.Name,
		&i.Category,
		&i.Quantity,
		&i.Unit,
		&i.ExpiryDate,
		&i.Calories,
		&i.Protein,
		&i.Fat,
		&i.Carbs,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

