// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shopping_and_recipes.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearShoppingList = `-- name: ClearShoppingList :exec
DELETE FROM shopping_items
WHERE fridge_id = $1
`

func (q *Queries) ClearShoppingList(ctx context.Context, fridgeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearShoppingList, fridgeID)
	return err
}

const createSavedRecipe = `-- name: CreateSavedRecipe :one
INSERT INTO saved_recipes (
    user_id, fridge_id, title, description, ingredients, steps,
    calories, protein, fat, carbs, prep_time_mins, cook_time_mins, servings
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, user_id, fridge_id, title, description, ingredients, steps, calories, protein, fat, carbs, prep_time_mins, cook_time_mins, servings, created_at
`

type CreateSavedRecipeParams struct {
	UserID       uuid.UUID
	FridgeID     pgtype.UUID
	Title        string
	Description  string
	Ingredients  []byte
	Steps        []byte
	Calories     int32
	Protein      float64
	Fat          float64
	Carbs        float64
	PrepTimeMins int32
	CookTimeMins int32
	Servings     int32
}

func (q *Queries) CreateSavedRecipe(ctx context.Context, arg CreateSavedRecipeParams) (SavedRecipe, error) {
	row := q.db.QueryRow(ctx, createSavedRecipe,
		arg.UserID,
		arg.FridgeID,
		arg.Title,
		arg.Description,
		arg.Ingredients,
		arg.Steps,
		arg.Calories,
		arg.Protein,
		arg.Fat,
		arg.Carbs,
		arg.PrepTimeMins,
		arg.CookTimeMins,
		arg.Servings,
	)
	var i SavedRecipe
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FridgeID,
		&i.Title,
		&i.Description,
		&i.Ingredients,
		&i.Steps,
		&i.Calories,
		&i.Protein,
		&i.Fat,
		&i.Carbs,
		&i.PrepTimeMins,
		&i.CookTimeMins,
		&i.Servings,
		&i.CreatedAt,
	)
	return i, err
}

const createShoppingItem = `-- name: CreateShoppingItem :one
INSERT INTO shopping_items (
    fridge_id, name, category, quantity, unit, is_bought, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, fridge_id, name, category, quantity, unit, is_bought, created_by, created_at, updated_at
`

type CreateShoppingItemParams struct {
	FridgeID  uuid.UUID
	Name      string
	Category  string
	Quantity  float64
	Unit      string
	IsBought  bool
	CreatedBy uuid.UUID
}

func (q *Queries) CreateShoppingItem(ctx context.Context, arg CreateShoppingItemParams) (ShoppingItem, error) {
	row := q.db.QueryRow(ctx, createShoppingItem,
		arg.FridgeID,
		arg.Name,
		arg.Category,
		arg.Quantity,
		arg.Unit,
		arg.IsBought,
		arg.CreatedBy,
	)
	var i ShoppingItem
	err := row.Scan(
		&i.ID,
		&i.FridgeID,
		&i.Name,
		&i.Category,
		&i.Quantity,
		&i.Unit,
		&i.IsBought,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBoughtShoppingItems = `-- name: DeleteBoughtShoppingItems :exec
DELETE FROM shopping_items
WHERE fridge_id = $1 AND is_bought = TRUE
`

func (q *Queries) DeleteBoughtShoppingItems(ctx context.Context, fridgeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBoughtShoppingItems, fridgeID)
	return err
}

const deleteSavedRecipe = `-- name: DeleteSavedRecipe :exec
DELETE FROM saved_recipes
WHERE id = $1 AND (fridge_id = $2 OR (fridge_id IS NULL AND user_id = $3))
`

type DeleteSavedRecipeParams struct {
	ID       uuid.UUID
	FridgeID pgtype.UUID
	UserID   uuid.UUID
}

func (q *Queries) DeleteSavedRecipe(ctx context.Context, arg DeleteSavedRecipeParams) error {
	_, err := q.db.Exec(ctx, deleteSavedRecipe, arg.ID, arg.FridgeID, arg.UserID)
	return err
}

const deleteShoppingItem = `-- name: DeleteShoppingItem :exec
DELETE FROM shopping_items
WHERE id = $1 AND fridge_id = $2
`

type DeleteShoppingItemParams struct {
	ID       uuid.UUID
	FridgeID uuid.UUID
}

func (q *Queries) DeleteShoppingItem(ctx context.Context, arg DeleteShoppingItemParams) error {
	_, err := q.db.Exec(ctx, deleteShoppingItem, arg.ID, arg.FridgeID)
	return err
}

const getSavedRecipeByID = `-- name: GetSavedRecipeByID :one
SELECT id, user_id, fridge_id, title, description, ingredients, steps, calories, protein, fat, carbs, prep_time_mins, cook_time_mins, servings, created_at FROM saved_recipes
WHERE id = $1 AND (fridge_id = $2 OR (fridge_id IS NULL AND user_id = $3))
`

type GetSavedRecipeByIDParams struct {
	ID       uuid.UUID
	FridgeID pgtype.UUID
	UserID   uuid.UUID
}

func (q *Queries) GetSavedRecipeByID(ctx context.Context, arg GetSavedRecipeByIDParams) (SavedRecipe, error) {
	row := q.db.QueryRow(ctx, getSavedRecipeByID, arg.ID, arg.FridgeID, arg.UserID)
	var i SavedRecipe
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FridgeID,
		&i.Title,
		&i.Description,
		&i.Ingredients,
		&i.Steps,
		&i.Calories,
		&i.Protein,
		&i.Fat,
		&i.Carbs,
		&i.PrepTimeMins,
		&i.CookTimeMins,
		&i.Servings,
		&i.CreatedAt,
	)
	return i, err
}

const getShoppingItemByID = `-- name: GetShoppingItemByID :one
SELECT id, fridge_id, name, category, quantity, unit, is_bought, created_by, created_at, updated_at FROM shopping_items
WHERE id = $1 AND fridge_id = $2
`

type GetShoppingItemByIDParams struct {
	ID       uuid.UUID
	FridgeID uuid.UUID
}

func (q *Queries) GetShoppingItemByID(ctx context.Context, arg GetShoppingItemByIDParams) (ShoppingItem, error) {
	row := q.db.QueryRow(ctx, getShoppingItemByID, arg.ID, arg.FridgeID)
	var i ShoppingItem
	err := row.Scan(
		&i.ID,
		&i.FridgeID,
		&i.Name,
		&i.Category,
		&i.Quantity,
		&i.Unit,
		&i.IsBought,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSavedRecipesByFridge = `-- name: ListSavedRecipesByFridge :many
SELECT id, user_id, fridge_id, title, description, ingredients, steps, calories, protein, fat, carbs, prep_time_mins, cook_time_mins, servings, created_at FROM saved_recipes
WHERE fridge_id = $1 OR (fridge_id IS NULL AND user_id = $2)
ORDER BY created_at DESC
`

type ListSavedRecipesByFridgeParams struct {
	FridgeID pgtype.UUID
	UserID   uuid.UUID
}

func (q *Queries) ListSavedRecipesByFridge(ctx context.Context, arg ListSavedRecipesByFridgeParams) ([]SavedRecipe, error) {
	rows, err := q.db.Query(ctx, listSavedRecipesByFridge, arg.FridgeID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SavedRecipe
	for rows.Next() {
		var i SavedRecipe
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FridgeID,
			&i.Title,
			&i.Description,
			&i.Ingredients,
			&i.Steps,
			&i.Calories,
			&i.Protein,
			&i.Fat,
			&i.Carbs,
			&i.PrepTimeMins,
			&i.CookTimeMins,
			&i.Servings,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShoppingItemsByFridge = `-- name: ListShoppingItemsByFridge :many
SELECT id, fridge_id, name, category, quantity, unit, is_bought, created_by, created_at, updated_at FROM shopping_items
WHERE fridge_id = $1
ORDER BY is_bought ASC, created_at DESC
`

func (q *Queries) ListShoppingItemsByFridge(ctx context.Context, fridgeID uuid.UUID) ([]ShoppingItem, error) {
	rows, err := q.db.Query(ctx, listShoppingItemsByFridge, fridgeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShoppingItem
	for rows.Next() {
		var i ShoppingItem
		if err := rows.Scan(
			&i.ID,
			&i.FridgeID,
			&i.Name,
			&i.Category,
			&i.Quantity,
			&i.Unit,
			&i.IsBought,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleShoppingItemBought = `-- name: ToggleShoppingItemBought :one
UPDATE shopping_items
SET is_bought = $3,
    updated_at = NOW()
WHERE id = $1 AND fridge_id = $2
RETURNING id, fridge_id, name, category, quantity, unit, is_bought, created_by, created_at, updated_at
`

type ToggleShoppingItemBoughtParams struct {
	ID       uuid.UUID
	FridgeID uuid.UUID
	IsBought bool
}

func (q *Queries) ToggleShoppingItemBought(ctx context.Context, arg ToggleShoppingItemBoughtParams) (ShoppingItem, error) {
	row := q.db.QueryRow(ctx, toggleShoppingItemBought, arg.ID, arg.FridgeID, arg.IsBought)
	var i ShoppingItem
	err := row.Scan(
		&i.ID,
		&i.FridgeID,
		&i.Name,
		&i.Category,
		&i.Quantity,
		&i.Unit,
		&i.IsBought,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateShoppingItem = `-- name: UpdateShoppingItem :one
UPDATE shopping_items
SET name = $3,
    category = $4,
    quantity = $5,
    unit = $6,
    is_bought = $7,
    updated_at = NOW()
WHERE id = $1 AND fridge_id = $2
RETURNING id, fridge_id, name, category, quantity, unit, is_bought, created_by, created_at, updated_at
`

type UpdateShoppingItemParams struct {
	ID       uuid.UUID
	FridgeID uuid.UUID
	Name     string
	Category string
	Quantity float64
	Unit     string
	IsBought bool
}

func (q *Queries) UpdateShoppingItem(ctx context.Context, arg UpdateShoppingItemParams) (ShoppingItem, error) {
	row := q.db.QueryRow(ctx, updateShoppingItem,
		arg.ID,
		arg.FridgeID,
		arg.Name,
		arg.Category,
		arg.Quantity,
		arg.Unit,
		arg.IsBought,
	)
	var i ShoppingItem
	err := row.Scan(
		&i.ID,
		&i.FridgeID,
		&i.Name,
		&i.Category,
		&i.Quantity,
		&i.Unit,
		&i.IsBought,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
